import type { DeviceListItem, PairingCodeClaimResponse } from '@focus-tracker/shared';
import { api } from './api';

// Thin typed wrappers around `/v1/devices/*`. Owned by Settings → Devices
// (`Settings.md` §4.4) but kept in lib/ so future surfaces (e.g. the
// post-pair toast on the Dashboard) can call them too.
//
// Query keys are co-located here so any component that mutates a device
// can invalidate the list with a stable key.

export const devicesQueryKeys = {
  all: ['devices'] as const,
  list: () => [...devicesQueryKeys.all, 'list'] as const,
};

export async function listDevices(): Promise<DeviceListItem[]> {
  const res = await api.get<DeviceListItem[]>('/v1/devices');
  return res.data;
}

export async function revokeDevice(deviceId: string): Promise<void> {
  await api.delete(`/v1/devices/${encodeURIComponent(deviceId)}`);
}

/// Claims a pairing code on behalf of the logged-in user. The code itself
/// was generated by the device (extension / desktop app) — the web app's
/// only job is to bind it to this account by hitting the JWT-guarded
/// `/claim` endpoint. See Auth.md §5.1 and the spec for the user flow in
/// Settings.md §4.4.
export async function claimPairingCode(code: string): Promise<PairingCodeClaimResponse> {
  const res = await api.post<PairingCodeClaimResponse>(
    `/v1/devices/pairing-codes/${encodeURIComponent(code)}/claim`,
  );
  return res.data;
}
